# Numpy is a general purpose array processing package 

# which provoides tools for handling the n-dimentional array

# Numpy is written in C & Python

# Its stands for "Numerical Python" allow to store data in multi diametional array.

# It is a table of elements (usally numbers), all of the same type

In [38]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [3]:
    import numpy as np

# Create Array


In [17]:
np_array = np.array([1,2,3,4,5]) #it is one dimentional array

In [18]:
np_array

array([1, 2, 3, 4, 5])

# Array of zero

In [21]:
Zero_array = np.zeros(6) #array of zero of 3 time

In [22]:
Zero_array

array([0., 0., 0., 0., 0., 0.])

# Array of 1

In [23]:
ones_array = np.ones(4)

In [24]:
ones_array

array([1., 1., 1., 1.])

# linSpace Array 

In [25]:
space_array = np.linspace(5,40,8) #produce number to 12 time between 7 to 40

In [27]:
space_array

array([ 5., 10., 15., 20., 25., 30., 35., 40.])

# Generate random number

In [32]:
random_array = np.random.randint(1,100, 20) # random intiger number

In [33]:
random_array

array([16, 90, 84, 24,  6, 85, 12, 60, 74, 51, 61, 57, 55, 70, 81, 28, 70,
       38, 70, 92])

# 6. Convert array into List

In [35]:
np_array = np.array([2,1,5,3,4])

In [36]:
np_array

array([2, 1, 5, 3, 4])

In [37]:
np_list = np_array.tolist()

In [38]:
np_list

[2, 1, 5, 3, 4]

# Higher Diamentional array

# 2D Array

In [42]:
np_2D_array = np.array([[1,2,3],
                      [6,4,2],
                      [9,7,1]])

In [43]:
np_2D_array

array([[1, 2, 3],
       [6, 4, 2],
       [9, 7, 1]])

# Reshape

In [45]:
np_transpose = np.array(range(25)).reshape(5,5)

In [46]:
np_transpose

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
 np.array(range(25))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

# 3D Array

In [47]:
np_3D_array = np.array([[[1,2,3],
                        [6,4,6],
                        [6,4,8]],
                        [[3,5,7],
                        [4,7,9],
                        [6,7,4]],
                        [[4,7,9],
                        [5,7,9],
                        [5,7,3]]])

In [48]:
np_3D_array

array([[[1, 2, 3],
        [6, 4, 6],
        [6, 4, 8]],

       [[3, 5, 7],
        [4, 7, 9],
        [6, 7, 4]],

       [[4, 7, 9],
        [5, 7, 9],
        [5, 7, 3]]])

# Numpy Operation

# type

In [50]:
a = type(np_array) #it show subclass of numpy (ndarray)

In [51]:
a

numpy.ndarray

In [49]:
np_array

array([2, 1, 5, 3, 4])

# min max argmax argmin

In [52]:
np_array = np.array([2,1,5,3,4])

In [53]:
np_array

array([2, 1, 5, 3, 4])

In [56]:
np_max = np_array.max()

In [57]:
np_max

5

In [58]:
np_argmax = np_array.argmax() #retrun Index value of max number

In [59]:
np_argmax

2

In [60]:
np_argmin = np_array.argmin() #retrun Index value of min number

In [61]:
np_argmin

1

# sort

In [63]:
np_sort = np.sort(np_array) #this will sort and retrun a copy of array

In [62]:
np_array

array([2, 1, 5, 3, 4])

In [88]:
np_sort

array([1, 2, 3, 4, 5])

In [65]:
np_array

array([2, 1, 5, 3, 4])

In [101]:
dummy = np.array([1,5,6,4,5,3])

In [101]:
np_order = np.sort(d)[::-1]

In [102]:
dummy.sort() #this will sort orgnal data

In [103]:
dummy

array([1, 3, 4, 5, 5, 6])

# sorting 2D array

In [104]:
np_2D_array = np.array([[1,2,3],
                      [6,4,2],
                      [9,7,1]])

In [105]:
np_2D_array

array([[1, 2, 3],
       [6, 4, 2],
       [9, 7, 1]])

In [108]:
sort_2d = np.sort(np_2D_array, axis=0) #sort by row element axis=1 and 0-for column element

In [109]:
sort_2d

array([[1, 2, 1],
       [6, 4, 2],
       [9, 7, 3]])

# Mean Std Log

In [113]:
np_mean = np.mean(np_array)

In [115]:
np_std = np.std(np_array)

In [137]:
np_log = np.log(np_array)

# Some Mathmetical Operations

In [110]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

In [111]:
np_add = array1+array2

In [112]:
np_add

array([5, 7, 9])

In [113]:
np_sub = array2-array1

In [114]:
np_sub

array([3, 3, 3])

In [115]:
np_mul = array1*array2

In [116]:
np_mul

array([ 4, 10, 18])

In [117]:
np_devi = array1/array2

In [118]:
np_devi

array([0.25, 0.4 , 0.5 ])

# Exponancial

In [120]:
np_exp = array1**2

In [119]:
array1

array([1, 2, 3])

In [121]:
np_exp

array([1, 4, 9], dtype=int32)

# Copy

In [122]:
np_2D_array = np.array([[1,2,3],
                      [6,4,2],
                      [9,7,1]])

In [123]:
copy_array = np_2D_array.copy()

In [124]:
copy_array

array([[1, 2, 3],
       [6, 4, 2],
       [9, 7, 1]])

In [125]:
np_2D_array

array([[1, 2, 3],
       [6, 4, 2],
       [9, 7, 1]])

# Indexing and Slicing

# Whenever we play with indexing and slicing it is not creating a copy but give view

In [137]:
np_array_new = np.array([12,5,-2,29,21])

In [141]:
np_array_new[2:4] # from indexing possition 2

array([-2, 29])

In [142]:
no_order = np_array_new[::-1]

In [143]:
no_order

array([21, 29, -2,  5, 12])

In [144]:
np_slice1 = np_array_new[-2:-1] # from last second element

In [145]:
np_slice1

array([29])

In [146]:
np_slice2 = np_array_new[:4] #start from 0 to index 3

In [147]:
np_slice2

array([12,  5, -2, 29])

# Copy 

In [149]:
np_copy = np_array_new[1:3].copy()

In [150]:
np_copy

array([ 5, -2])

# Insert number into array

In [152]:
np_copy[:] = 5

In [153]:
np_copy

array([5, 5])

# Slicing 2D array

In [155]:
np_2D_array = np.array([[1,2,3],
                      [6,4,2],
                      [9,7,1]])

In [156]:
slice_2D_1 = np_2D_array[:2,:2]

In [157]:
slice_2D_1

array([[1, 2],
       [6, 4]])

In [158]:
slice_2D_2 = np_2D_array[:,1:]

In [159]:
slice_2D_2

array([[2, 3],
       [4, 2],
       [7, 1]])

In [160]:
slice_2D_3 = np_2D_array[1:,1:]

In [161]:
slice_2D_3

array([[4, 2],
       [7, 1]])

# Thank You